[main]

capslock = overload(vim, esc)

[control]

n = down

p = up

[shift]

capslock = capslock

[vim]

# arrow keys
h = left
j = down
k = up
l = right

# forward word
w = C-right

# backward word
b = C-left
